version: '3'
services:
  node:
    build:
      context: .
    tty: true
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd sample && npm start" 
    ports:
    - "3000:3000"